name: Publish DockerHub Image

on: [ workflow_dispatch ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest .
    - name: publish
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
